export const eng = {
  titles: {
    trainingList: 'Training List',
    createTrainingSession: 'Create Training Session',
    training: 'Training',
    settings: 'Settings',
  },
  trainingsList: {
    exercises: 'Exercises',
    totalTime: 'Total time',
    rounds: 'Rounds',
    startNow: 'Start Now',
    edit: 'Edit',
    delete: 'Delete',
  },
  createTrainingSession: {
    tsNamePlaceholder: 'Training Session Name',
    blockName: 'Block Name',
    blockDefault: 'Exercise',
    workMin: 'Work Min',
    workSec: 'Work Sec',
    restMin: 'Rest Min',
    restSec: 'Rest sec',
    rounds: 'Rounds',
    delete: 'Delete Exercise',
    addExercise: 'Add Exercise',
    saveTraining: 'Save Training',
  },
  training: {
    addSomeRounds: 'Add some rounds first',
    exerciseComplete: 'Ejercicio Completado!!!',
    totalTime: 'Total Time',
    work: 'Work',
    rest: 'Rest',
    rounds: 'Rounds',
    of: 'of',
    start: 'Start',
    pause: 'Pause',
    reset: 'Reset',
  },
  settings: {
    soundSet: 'Sound Set',
    bells_small: 'Small Bells',
    bells_med: 'Medium Bells',
    sport_whistle: 'Sports Whistle',
    cartoon_whistle: 'Cartoons Whistle',
    language: 'Language',
    english: 'English',
    spanish: 'Spanish',
  },
};

export const sp = {
  titles: {
    trainingList: 'Lista de Entrenamientos',
    createTrainingSession: 'Crear Entrenamiento',
    training: 'Entrenamiento',
    settings: 'Configuración',
  },
  trainingsList: {
    exercises: 'Ejercicios',
    totalTime: 'Tiempo Total',
    rounds: 'Rounds',
    startNow: 'Empezar Ahora',
    edit: 'Editar',
    delete: 'Borrar',
  },
  createTrainingSession: {
    tsNamePlaceholder: 'Nombre de Entrenamiento',
    blockName: 'Nombre de Bloque',
    blockDefault: 'Ejercicio',
    workMin: 'Mins Trabajo',
    workSec: 'Segs Trabajo',
    restMin: 'Mins Descanso',
    restSec: 'Segs Descanso',
    rounds: 'Rounds',
    delete: 'Borrar Ejercicio',
    addExercise: 'Agregar Ejercicio',
    saveTraining: 'Guardar Entrenamiento',
  },
  training: {
    addSomeRounds: 'Agregá unos rounds primero',
    totalTime: 'Tiempo Total',
    work: 'Entrenar!!',
    rest: 'Descansar!!',
    rounds: 'Rounds',
    of: 'de',
    start: 'Empezar',
    pause: 'Pausa',
    reset: 'Reiniciar',
  },
  settings: {
    soundSet: 'Sonidos',
    bells_small: 'Campanitas',
    bells_med: 'Campanas',
    sport_whistle: 'Silbato Deportivo',
    cartoon_whistle: 'Silbato Dibujitos',
    language: 'Lenguaje',
    english: 'Inglés',
    spanish: 'Español',
  },
};
